const games=[
{name:'Noodle Arrows',image:'noodle.jpg',video:'noodle.mp4',genre:'Logic puzzle',line:'A colorful tangle. One satisfying way out.',description:'Find the arrows that can slide free, plan your next move, and untangle the board. Every cleared path brings you one step closer to that perfectly solved feeling.'},
{name:'Prism Pour',image:'prism.jpg',video:'prism.mp4',genre:'Color sorting',line:'Find a little order in a world of color.',description:'Pour, plan, and bring every color together. Sort the layered liquids until each tube holds a single color, with a satisfying splash along the way.'},
{name:'Seat Sleuth',image:'seat.jpg',video:'seat.mp4',genre:'Deduction puzzle',line:'Every guest has a place. Can you find it?',description:'Meet a charming cast of guests and use their clues to work out who sits where. A little observation and a clever deduction can make everyone happy.'},
{name:'Tiny Wick',image:'tiny.jpg',video:'tiny.mp4',genre:'Survival adventure',line:'One tiny flame against a whole lot of darkness.',description:'Keep your flame alive as the shadows close in. Mix spells, face ghostly enemies, and turn a small candle into a bright little force of nature.'},
{name:'Munch Loop',image:'munch-keyart.jpg',video:'munch.mp4',genre:'Arcade puzzle',line:'Hungry little friends. Deliciously colorful puzzles.',description:'Feed the Munchies and clear the picture. Colorful blocks, playful characters, and a looping puzzle challenge come together in a satisfying bite-sized adventure.'},
{name:'Boop Blocks',image:'boop-keyart.jpg',video:'boop.mp4',genre:'3D puzzle',line:'Spin it. Tap it. Boop every block out.',description:'Rotate colorful 3D sculptures and find the blocks with a clear path. Tap them out in the right order, avoid bumps that cost a heart, and explore 200 sculptures full of satisfying little discoveries.'}
];
const grid=document.querySelector('#game-grid');const reduced=matchMedia('(prefers-reduced-motion: reduce)');const motion=document.querySelector('#motion');const dialog=document.querySelector('#details');let previousFocus;let hoveredCard=null;let visibleCard=null;
function paused(){return document.body.classList.contains('paused')||document.hidden||dialog.open}
games.forEach((g,i)=>{g.preview=g.video?.replace('.mp4','-preview.mp4');const b=document.createElement('button');b.className='game-card reveal';b.setAttribute('aria-label',`Explore ${g.name}`);b.innerHTML=`<div class="game-image"><img loading="lazy" src="assets/${g.image}" alt="${g.name} game artwork" width="1280" height="720">${g.preview?`<video class="card-video" muted loop playsinline preload="none" poster="assets/${g.image}" data-src="assets/${g.preview}" aria-hidden="true"></video>`:''}<span class="number">0${i+1}</span>${g.video?'<span class="card-play" aria-hidden="true">▶</span>':''}</div><div class="game-info"><h3>${g.name}</h3><span class="tag">${g.genre}</span></div><p>${g.line}</p><span class="game-link">${g.video?'Watch trailer':'Explore game'}</span>`;b.addEventListener('click',()=>openGame(g));b.addEventListener('mouseenter',()=>{hoveredCard=b;syncCards()});b.addEventListener('mouseleave',()=>{hoveredCard=null;syncCards()});b.addEventListener('focus',()=>{hoveredCard=b;syncCards()});b.addEventListener('blur',()=>{hoveredCard=null;syncCards()});b.querySelector('video')?.addEventListener('error',()=>b.classList.remove('previewing'));grid.appendChild(b)});
function syncCards(){const candidate=matchMedia('(hover:hover)').matches?hoveredCard:visibleCard;document.querySelectorAll('.card-video').forEach(v=>{const b=v.closest('.game-card');if(b===candidate&&!paused()){if(!v.hasAttribute('src'))v.src=v.dataset.src;v.muted=true;v.play().then(()=>{if(!v.paused&&!paused())b.classList.add('previewing')}).catch(()=>{b.classList.remove('previewing')})}else{v.pause();b.classList.remove('previewing')}})}
const cardVisibility=new Map();
const mobileObs=new IntersectionObserver(es=>{es.forEach(e=>cardVisibility.set(e.target,e.intersectionRatio));visibleCard=[...cardVisibility].filter(x=>x[1]>.65).sort((a,b)=>b[1]-a[1])[0]?.[0]||null;syncCards()},{threshold:[0,.65,.9]});document.querySelectorAll('.game-card').forEach(b=>mobileObs.observe(b));
function openGame(g){previousFocus=document.activeElement;document.querySelector('#detail-content').innerHTML=`${g.video?`<video class="modal-media" controls playsinline preload="metadata" poster="assets/${g.image}" src="assets/${g.video}" aria-label="${g.name} full launch trailer"></video>`:`<img class="modal-media" src="assets/${g.image}" alt="${g.name}">`}<div class="modal-copy"><p class="eyebrow">${g.genre}</p><h2 id="detail-title">${g.name}</h2><p>${g.description}</p></div>`;dialog.showModal();document.body.style.overflow='hidden';syncAll()}
document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{dialog.querySelector('video')?.pause();document.body.style.overflow='';previousFocus?.focus();syncAll()});
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>obs.observe(e));
const preview=document.querySelector('#feature-video');let featuredIndex=2;let previewVisible=false;
function syncAll(){if(previewVisible&&!paused())preview.play().catch(()=>{});else preview.pause();syncCards()}
function setPaused(value){document.body.classList.toggle('paused',value);motion.textContent=value?'Resume motion':'Pause motion';motion.setAttribute('aria-pressed',String(value));syncAll()}
motion.addEventListener('click',()=>setPaused(!document.body.classList.contains('paused')));if(reduced.matches)setPaused(true);reduced.addEventListener('change',e=>setPaused(e.matches));
new IntersectionObserver(es=>{previewVisible=es[0].isIntersecting;syncAll()},{threshold:.2}).observe(preview);document.addEventListener('visibilitychange',syncAll);
preview.addEventListener('timeupdate',()=>{document.querySelector('#video-progress').style.width=(preview.duration?preview.currentTime/preview.duration*100:0)+'%'});
document.querySelectorAll('.feature-picker button').forEach(b=>b.addEventListener('click',()=>{featuredIndex=Number(b.dataset.game);const g=games[featuredIndex];preview.poster='assets/'+g.image;preview.src='assets/'+g.preview;preview.setAttribute('aria-label',g.name+' gameplay');document.querySelector('#feature-name').textContent=g.name;document.querySelector('#feature-genre').textContent=g.genre.toUpperCase();document.querySelector('#feature-line').textContent=g.line;document.querySelector('#feature-count').textContent=String(featuredIndex+1).padStart(2,'0');document.querySelectorAll('.feature-picker button').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});syncAll()}));document.querySelector('#feature-trailer').addEventListener('click',()=>openGame(games[featuredIndex]));
document.querySelector('#surprise').addEventListener('click',()=>openGame(games[Math.floor(Math.random()*games.length)]));
